registration_types.registration_type.*:
  type: config_entity
  label: 'Registration type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    enabled:
      type: boolean
      label: 'Enabled'
    display:
      type: string
      label: 'Display'
    custom_path:
      type: string
      label: 'Custom path'
    tab_title:
      type: string
      label: 'Tab title'
    roles:
      label: 'Assigned roles'
      type: sequence
      sequence:
        type: string
    page_title:
      type: string
      label: 'Page title'
    description:
      type: string
      label: 'Description'
