definitions:
  contact__site_page:
    weight: -47
    menu_name: secondary
    parent: ''
    expanded: false
    enabled: true
  standard__front_page:
    enabled: false
    menu_name: main
    parent: ''
    expanded: false
    weight: -50
  user__logout:
    weight: -44
    menu_name: secondary
    parent: ''
    expanded: false
    enabled: true
  user__page:
    weight: -50
    menu_name: secondary
    parent: ''
    expanded: false
    enabled: true
_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
