block.settings.menu_block:*:
  type: block_settings
  label: 'Menu block'
  mapping:
    level:
      type: integer
      label: 'Starting level'
    depth:
      type: integer
      label: 'Maximum number of levels'
    expanded:
      type: boolean
      label: 'Expand all menu links'
    parent:
      type: string
      label: 'Parent menu link'
    fixed_to_level:
      type: boolean
      label: 'Fixed parent starting level'
    suggestion:
      type: string
      label: 'Theme suggestion'
